name: Release registry image

env:
  CI: true
on:
  push:
    branches:
      - main
    tags:
      - "!*"
jobs:
  release:
    name: Setup
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'

      - name: Restore dependencies
        run: |
          yarn install

      - name: Build packages
        run: |
          yarn build

      - name: Prepare Docker build
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          npm run docker:prepare
          docker buildx inspect --bootstrap

      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Docker Build & Push
        run: npm run docker:build
        env:
          PACKAGES_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          body_path: RELEASE_NOTES.md
          tag_name: v${{ env.PACKAGE_VERSION }}
