name: Build registry image snapshot

env:
  CI: true
on:
  push:
    branches:
      - development
    tags:
      - "!*"
jobs:
  snapshot:
    name: Setup
    runs-on: ubuntu-24.0.4
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 20

      - name: Restore dependencies
        run: |
          yarn install

      - name: Build packages
        run: |
          yarn build

      - name: Prepare Docker build
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          npm run docker:prepare
          docker buildx inspect --bootstrap

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Push
        run: npm run docker:build:snapshot
